#!/usr/bin/env python3
"""Build the committed ChatGPT Builder instructions and knowledge bundle."""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EDITION = ROOT / "chatgpt-edition"
GENERATED_NOTICE = "<!-- Generated by scripts/build_chatgpt_edition.py; edit the source files instead. -->\n\n"
MARKDOWN_LINK = re.compile(r"(\]\()([^\s)]+)([^)]*\))")


def source_paths() -> list[Path]:
    paths: list[Path] = []
    for raw in (EDITION / "knowledge-sources.txt").read_text(encoding="utf-8").splitlines():
        value = raw.strip()
        if not value or value.startswith("#"):
            continue
        path = (ROOT / value).resolve()
        if not path.is_relative_to(ROOT) or path.suffix.lower() != ".md":
            raise ValueError(f"unsafe knowledge source path: {value}")
        if not path.is_file():
            raise ValueError(f"missing knowledge source: {value}")
        paths.append(path)
    if not paths:
        raise ValueError("knowledge source list is empty")
    return paths


def rebase_links(content: str, source: Path) -> str:
    """Keep copied repository links valid from the generated bundle location."""

    def replace(match: re.Match[str]) -> str:
        raw = match.group(2).strip("<>")
        if raw.startswith("#") or re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", raw):
            return match.group(0)
        path_part, separator, fragment = raw.partition("#")
        destination = (source.parent / path_part).resolve()
        if not destination.is_relative_to(ROOT):
            raise ValueError(f"knowledge link escapes repository: {raw}")
        relative = os.path.relpath(destination, EDITION).replace(os.sep, "/")
        rebased = relative + (separator + fragment if separator else "")
        return match.group(1) + rebased + match.group(3)

    return MARKDOWN_LINK.sub(replace, content)


def render() -> dict[Path, str]:
    policy = (ROOT / "references" / "core-teaching-policy.md").read_text(encoding="utf-8").strip()
    template = (EDITION / "instructions-source.md").read_text(encoding="utf-8")
    if template.count("{{CORE_TEACHING_POLICY}}") != 1:
        raise ValueError("instructions source must contain exactly one core-policy placeholder")
    instructions = GENERATED_NOTICE + template.replace("{{CORE_TEACHING_POLICY}}", policy).strip() + "\n"

    sections = [
        "# Teach Me for ChatGPT knowledge\n\n"
        "This owner-uploaded knowledge bundle is generated from the repository sources listed in "
        "`chatgpt-edition/knowledge-sources.txt`. It contains teaching policy, not learner records, "
        "hidden answer keys, evaluation fixtures, or deterministic guards."
    ]
    for path in source_paths():
        relative = path.relative_to(ROOT).as_posix()
        body = rebase_links(path.read_text(encoding="utf-8").strip(), path)
        sections.append(f"# Source: {relative}\n\n{body}")
    knowledge = GENERATED_NOTICE + "\n\n---\n\n".join(sections).strip() + "\n"
    return {EDITION / "INSTRUCTIONS.md": instructions, EDITION / "KNOWLEDGE.md": knowledge}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if committed outputs are stale")
    args = parser.parse_args()
    outputs = render()
    stale: list[str] = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.write_text(content, encoding="utf-8")
    if stale:
        print("ChatGPT Edition generated files are stale: " + ", ".join(stale), file=sys.stderr)
        return 1
    print("Teach Me for ChatGPT bundle is current")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ValueError as exc:
        print(f"ChatGPT Edition build failed: {exc}", file=sys.stderr)
        raise SystemExit(1)
